<?php
?>

<body>
	<h3>Progress</h3>

	<div class='levelOne'>
		<span>Suicide Pools Page</span>
		<span class='percentage'></span>
		<span class='difficulty'></span>

		<div class='levelTwo'>
			<span>Wizard to Allow User to Create Pools</span>
			<span class='percentage'></span>
			<span class='difficulty'></span>

			<div class='levelThree'>
				<span>Allow User to Specify Pool Name</span>
				<span class='percentage'>100</span>
				<span class='difficulty'>2</span>
			</div>

			<div class='levelThree'>
				<span>Throw Up Notice Modal Following Pool Creation</span>
				<span class='percentage'>85</span>
				<span class='difficulty'>1</span>
			</div>

			<div class='levelThree'>
				<span>Allow Manager to Change Default Settings</span>
				<span class='percentage'>0</span>
				<span class='difficulty'>2</span>
			</div>

			<div class='levelThree'>
				<span>Allow Manager to Invite Users</span>
				<span class='percentage'>0</span>
				<span class='difficulty'>2</span>
			</div>

		</div>

		<div class='levelTwo'>
			<span>Modal to Allow Pool Managers to Manage Members</span>
			<span class='percentage'></span>
			<span class='difficulty'></span>

			<div class='levelThree'>
				<span>Allow Manager to Search for Members</span>
				<span class='percentage'>60</span>
				<span class='difficulty'>1</span>
			</div>

			<div class='levelThree'>
				<span>Allow Manager to Invite Members</span>
				<span class='percentage'>0</span>
				<span class='difficulty'>2</span>
			</div>

			<div class='levelThree'>
				<span>Allow Manager to Invite Non-Members</span>
				<span class='percentage'>0</span>
				<span class='difficulty'>3</span>
			</div>

			<div class='levelThree'>
				<span>Generate Table of Members</span>
				<span class='percentage'>0</span>
				<span class='difficulty'>2</span>
			</div>

			<div class='levelThree'>
				<span>Filter on Table of Members</span>
				<span class='percentage'>0</span>
				<span class='difficulty'>1</span>
			</div>

			<div class='levelThree'>
				<span>Allow Managers to Kick Out Members</span>
				<span class='percentage'>0</span>
				<span class='difficulty'>1</span>
			</div>

			<div class='levelThree'>
				<span>Allow Managers to Resurrect Members</span>
				<span class='percentage'>0</span>
				<span class='difficulty'>3</span>
			</div>

			<div class='levelThree'>
				<span>Allow Managers to Resurrect Members that Died a Week Ago</span>
				<span class='percentage'>0</span>
				<span class='difficulty'>4</span>
			</div>

			<div class='levelThree'>
				<span>Allow Managers to Make Picks for Users That Authorized It</span>
				<span class='percentage'>0</span>
				<span class='difficulty'>5</span>
			</div>
		</div>

		<div class='levelTwo'>
			<span>Modal to Allow Pool Managers to Change Pool Settings</span>
			<span class='percentage'></span>
			<span class='difficulty'></span>

			<div class='levelThree'>
				<span>Allow Manager to Set Pool Description</span>
				<span class='percentage'>0</span>
				<span class='difficulty'>1</span>
			</div>

			<div class='levelThree'>
				<span>Allow Manager to Pass Off Manager Duties to Somebody Else</span>
				<span class='percentage'>0</span>
				<span class='difficulty'>2</span>
			</div>

			<div class='levelThree'>
				<span>Allow Manager to Dictate Number of Picks That Have to be Made</span>
				<span class='percentage'>40</span>
				<span class='difficulty'>1</span>
			</div>

			<div class='levelThree'>
				<span>Allow Manager to Set Deadline for when Picks Have to be Made for Any Given Week</span>
				<span class='percentage'>0</span>
				<span class='difficulty'>1</span>
			</div>

		</div>

		<div class='levelTwo'>
			<span>Modal to Allow Pool Members to Adjust Personal Settings</span>
			<span class='percentage'></span>
			<span class='difficulty'></span>

			<div class='levelThree'>
				<span>Allow Member to Adjust E-Mail Settings</span>
				<span class='percentage'>0</span>
				<span class='difficulty'>1</span>
			</div>

			<div class='levelThree'>
				<span>Allow Member to Allow Manager to Make Picks on his Behalf</span>
				<span class='percentage'>0</span>
				<span class='difficulty'>1</span>
			</div>

		</div>

		<div class='levelTwo'>
			<span>Send Out Notice E-Mails</span>
			<span class='percentage'></span>
			<span class='difficulty'></span>

			<div class='levelThree'>
				<span>Set Up Server-Side System to Send Notice E-mails</span>
				<span class='percentage'>0</span>
				<span class='difficulty'>2</span>
			</div>

			<div class='levelThree'>
				<span>Send Out Pool-wide E-mail Every Time Manager Changes Number of Picks to be Made</span>
				<span class='percentage'>0</span>
				<span class='difficulty'>1</span>
			</div>

			<div class='levelThree'>
				<span>Send Out Pool-wide E-mail Every Time Somebody has been Resurrected</span>
				<span class='percentage'>0</span>
				<span class='difficulty'>1</span>
			</div>

			<div class='levelThree'>
				<span>Send Out Pool-wide E-mail Every Time A Group Of People Have Been Resurrected</span>
				<span class='percentage'>0</span>
				<span class='difficulty'>1</span>
			</div>

			<div class='levelThree'>
				<span>Send Out Pool-wide E-mail Every Time Pick Deadline Has Been Changed</span>
				<span class='percentage'>0</span>
				<span class='difficulty'>1</span>
			</div>

			<div class='levelThree'>
				<span>Send Out Pool-wide E-mail Every Time a New Manager is Appointed</span>
				<span class='percentage'>0</span>
				<span class='difficulty'>1</span>
			</div>

		</div>

		<div class='levelTwo'>
			<span>Create Site-Wide Suicide Pool</span>
			<span class='percentage'></span>
			<span class='difficulty'></span>

			<div class='levelThree'>
				<span>Invite Every User Once They Sign Up</span>
				<span class='percentage'>0</span>
				<span class='difficulty'>1</span>
			</div>

			<div class='levelThree'>
				<span>Prioritize Suicide Pool on List of User's Pools</span>
				<span class='percentage'>0</span>
				<span class='difficulty'>2</span>
			</div>

		</div>

		<div class='levelTwo'>
			<span>Allow Pool Members Ability to Accept/Reject Invitations</span>
			<span class='percentage'>0</span>
			<span class='difficulty'>1</span>
		</div>

		<div class='levelTwo'>
			<span>Allow Pool Members Ability to Accept/Reject Invitations</span>
			<span class='percentage'>0</span>
			<span class='difficulty'>2</span>
		</div>

		<div class='levelTwo'>
			<span>Allow Pool Members Ability to Search and Apply to Pools</span>
			<span class='percentage'>0</span>
			<span class='difficulty'>2</span>
		</div>

	</div>

	<div class='levelOne'>
		<span>Progress Page</span>
		<span class='percentage'></span>
		<span class='difficulty'></span>

		<div class='levelTwo'>
			<span>Design Stylish Progress Bar</span>
			<span class='percentage'>100</span>
			<span class='difficulty'>1</span>
		</div>

		<div class='levelTwo'>
			<span>Script the Rendering of Progress Bar</span>
			<span class='percentage'>100</span>
			<span class='difficulty'>1</span>
		</div>

		<div class='levelTwo'>
			<span>All Other Script on Page</span>
			<span class='percentage'>100</span>
			<span class='difficulty'>1</span>
		</div>

		<div class='levelTwo'>
			<span>Populate the Page with Tasks</span>
			<span class='percentage'>20</span>
			<span class='difficulty'>1</span>
		</div>

		<div class='levelTwo'>
			<span>Server Logic to Prevent Access to Non-Admins</span>
			<span class='percentage'>0</span>
			<span class='difficulty'>1</span>
		</div>

	</div>

	<div class='levelOne'>
		<span>Log In / Forgot Password</span>
		<span class='percentage'></span>
		<span class='difficulty'></span>

		<div class='levelTwo'>
			<span>Allow User To Log In</span>
			<span class='percentage'></span>
			<span class='difficulty'></span>

			<div class='levelThree'>
				<span>Set Up Login View</span>
				<span class='percentage'>100</span>
				<span class='difficulty'>1</span>
			</div>

			<div class='levelThree'>
				<span>Set Up Server-Side Validation Logic</span>
				<span class='percentage'>100</span>
				<span class='difficulty'>1</span>
			</div>

			<div class='levelThree'>
				<span>Set Up Remember Me Logic</span>
				<span class='percentage'>100</span>
				<span class='difficulty'>2</span>
			</div>

			<div class='levelThree'>
				<span>Secure Log-In Cookie</span>
				<span class='percentage'>90</span>
				<span class='difficulty'>2</span>				
			</div>

			<div class='levelThree'>
				<span>Allow for Temporary Passwords to Reset Actual Passwords</span>
				<span class='percentage'>0</span>
				<span class='difficulty'>3</span>
			</div>

		</div>

		<div class='levelTwo'>
			<span>Forgot Password</span>
			<span class='percentage'></span>
			<span class='difficulty'></span>

			<div class='levelThree'>
				<span>Set Up Forgot Password View</span>
				<span class='percentage'>100</span>
				<span class='difficulty'>1</span>
			</div>

			<div class='levelThree'>
				<span>Animate Transition Between Login View and Forgot Password View</span>
				<span class='percentage'>100</span>
				<span class='difficulty'>1</span>
			</div>

			<div class='levelThree'>
				<span>Set Up Server-Side Validation Logic</span>
				<span class='percentage'>50</span>
				<span class='difficulty'>1</span>
			</div>

			<div class='levelThree'>
				<span>Send Out Forgot Password E-Mail</span>
				<span class='percentage'>100</span>
				<span class='difficulty'>1</span>
			</div>

			<div class='levelThree'>
				<span>Secure Database Against Spamming Attack</span>
				<span class='percentage'>70</span>
				<span class='difficulty'>2</span>
			</div>

		</div>

		<div class='levelTwo'>
			<span>Throw Up Error Modal Here to Display All Errors</span>
			<span class='percentage'>25</span>
			<span class='difficulty'>1</span>
		</div>

	</div>

	<div class='levelOne'>
		<span>Features</span>
		<span class='percentage'></span>
		<span class='difficulty'></span>

		<div class='levelTwo'>
			<span>Modals</span>
			<span class='percentage'></span>
			<span class='difficulty'></span>

			<div class='levelThree'>
				<span>Style Modal</span>
				<span class='percentage'>90</span>
				<span class='difficulty'>2</span>
			</div>

			<div class='levelThree'>
				<span>Script Logic for Opening and Closing of Modal</span>
				<span class='percentage'>80</span>
				<span class='difficulty'>1</span>
			</div>

			<div class='levelThree'>
				<span>Script Logic for Transitioning Between Modals</span>
				<span class='percentage'>75</span>
				<span class='difficulty'>1</span>
			</div>

			<div class='levelThree'>
				<span>Set Up an Exit Button in the Upper-Right Corner of Modals</span>
				<span class='percentage'>50</span>
				<span class='difficulty'>1</span>
			</div>

			<div class='levelThree'>
				<span>Script Logic for Nested Modals</span>
				<span class='percentage'>100</span>
				<span class='difficulty'>4</span>
			</div>

			<div class='levelThree'>
				<span>Define Small Modals</span>
				<span class='percentage'>100</span>
				<span class='difficulty'>1</span>
			</div>

			<div class='levelThree'>
				<span>Define Midsize Modals</span>
				<span class='percentage'>100</span>
				<span class='difficulty'>1</span>
			</div>

			<div class='levelThree'>
				<span>Large Modals</span>
				<span class='percentage'>0</span>
				<span class='difficulty'>1</span>
			</div>

		</div>

		<div class='levelTwo'>
			<span>Autocomplete</span>
			<span class='percentage'>100</span>
			<span class='difficulty'>2</span>
		</div>

		<div class='levelTwo'>
			<span>Error Handling</span>
			<span class='percentage'></span>
			<span class='difficulty'></span>

			<div class='levelThree'>
				<span>Error Modals</span>
				<span class='percentage'>60</span>
				<span class='difficulty'>2</span>
			</div>

			<div class='levelThree'>
				<span>Error Container</span>
				<span class='percentage'>30</span>
				<span class='difficulty'>2</span>
			</div>

			<div class='levelThree'>
				<span>Smart Logic to Handle Errors in as Generic a Manner as Possible</span>
				<span class='percentage'>0</span>
				<span class='difficulty'>1</span>
			</div>

		</div>

		<div class='levelTwo'>
			<span>Toggle Switch</span>
			<span class='percentage'>100</span>
			<span class='difficulty'>2</span>
		</div>

		<div class='levelTwo'>
			<span>Table Filtering</span>
			<span class='percentage'>0</span>
			<span class='difficulty'>1</span>
		</div>

		<div class='levelTwo'>
			<span>SuperTips</span>
			<span class='percentage'>100</span>
			<span class='difficulty'>5</span>
		</div>

		<div class='levelTwo'>
			<span>InfoTabs</span>
			<span class='percentage'>100</span>
			<span class='difficulty'>1</span>
		</div>

		<div class='levelTwo'>
			<span>Labels</span>
			<span class='percentage'>100</span>
			<span class='difficulty'>1</span>
		</div>

		<div class='levelTwo'>
			<span>Stylish Checkboxes</span>
			<span class='percentage'>100</span>
			<span class='difficulty'>1</span>
		</div>

	</div>

	<div class='levelOne'>
		<span>Maintenance / Infrastructure</span>
		<span class='percentage'></span>
		<span class='difficulty'></span>

		<div class='levelTwo'>
			<span>Better Organize All Sass Files</span>
			<span class='percentage'></span>
			<span class='difficulty'></span>

			<div class='levelThree'>
				<span>Better Modularize base.scss</span>
				<span class='percentage'>40</span>
				<span class='difficulty'>1</span>
			</div>

			<div class='levelThree'>
				<span>Better Organize/Modularize baseStyles.scss</span>
				<span class='percentage'>30</span>
				<span class='difficulty'>1</span>
			</div>

			<div class='levelThree'>
				<span>Better Organize the Rest of the Bunch</span>
				<span class='percentage'>15</span>
				<span class='difficulty'>5</span>
			</div>

			<div class='levelThree'>
				<span>Standardize a Base Set of Stylesheets to Include on Every Page</span>
				<span class='percentage'>30</span>
				<span class='difficulty'>1</span>
			</div>

		</div>

		<div class='levelTwo'>
			<span>Better Organize All View Files</span>
			<span class='percentage'></span>
			<span class='difficulty'></span>

			<div class='levelThree'>
				<span>Better Organize base.phtml</span>
				<span class='percentage'>0</span>
				<span class='difficulty'>1</span>
			</div>

			<div class='levelThree'>
				<span>Modularize View Files</span>
				<span class='percentage'>10</span>
				<span class='difficulty'>5</span>
			</div>

			<div class='levelThree'>
				<span>Allow for Multiple View Files to be Loaded on Any Page</span>
				<span class='percentage'>100</span>
				<span class='difficulty'>1</span>
			</div>

			<div class='levelThree'>
				<span>Merge All Utility View Files Into One File</span>
				<span class='percentage'>0</span>
				<span class='difficulty'>2</span>
			</div>


		</div>

		<div class='levelTwo'>
			<span>Organize all Third-Party Libraries Into Its Own Vendor Folder</span>
			<span class='percentage'>25</span>
			<span class='difficulty'>2</span>
		</div>

	</div>

	<div class='levelOne'>
		<span>Version 2.0</span>
		<span class='percentage'></span>
		<span class='difficulty'></span>

		<div class='levelTwo'>
			<span>Feature Enhancement</span>
			<span class='percentage'></span>
			<span class='difficulty'></span>

			<div class='levelThree'>
				<span>Autocomplete Arrow Key Integration</span>
				<span class='percentage'>0</span>
				<span class='difficulty'>2</span>
			</div>

		</div>

		<div class='levelTwo'>
			<span>Incorporate RequireJS</span>
			<span class='percentage'>0</span>
			<span class='difficulty'>5</span>
		</div>

	</div>

	<div class='levelOne'>
		<span>GitHub</span>
		<span class='percentage'></span>
		<span class='difficulty'></span>

		<div class='levelTwo'>
			<span>Install GitHub</span>
			<span class='percentage'>100</span>
			<span class='difficulty'>1</span>
		</div>

		<div class='levelTwo'>
			<span>Configure GitHub</span>
			<span class='percentage'>85</span>
			<span class='difficulty'>1</span>
		</div>

		<div class='levelTwo'>
			<span>Create GitHub Repository</span>
			<span class='percentage'>100</span>
			<span class='difficulty'>1</span>
		</div>

		<div class='levelTwo'>
			<span>Link to Repository from Work Comp</span>
			<span class='percentage'>50</span>
			<span class='difficulty'>1</span>
		</div>

	</div>

	<div class='levelOne'>
		<span>Bugs</span>
		<span class='percentage'></span>
		<span class='difficulty'></span>

		<div class='levelTwo'>
			<span>Disable Page Scrolling When Modal is Visible</span>
			<span class='percentage'>0</span>
			<span class='difficulty'>1</span>
		</div>

		<div class='levelTwo'>
			<span>Ensure That Nested Modals Have a Higher Z-Index than the Stronger Overlays</span>
			<span class='percentage'>0</span>
			<span class='difficulty'>1</span>
		</div>

	</div>

	<div class='heightener'></div>
</body>