<?php
	global $view;
?>
<html>
	<head>
		<meta charset="UTF-8" />
	<!-- Forcing IE to adhere to standards here -->
		<meta http-equiv="X-UA-Compatible" content="IE=Edge">

	<!-- Load all the CSS files for this page -->
		<?php
			foreach($view->css as $css)
			{
		?>
				<link rel="stylesheet" type="text/css" href='<?=$css ?>'/>
		<?php
			};
		?>
	</head>
	<body>
		<!-- Load all the foundation view files that will be displayed across all pages -->
		<?php
			foreach($view->foundationViews as $html)
			{
				TOS_REQUIRE_ONCE($html);
			}
		?>
		<div class='content'>
			<!-- Load all the view files that comprise the main content for this page -->
		<?php
			foreach($view->contentViews as $html)
			{
				TOS_REQUIRE_ONCE($html);
			}
			?>
		</div>

		<!--
			Configure the requireJS engine before using the library to pull external JavaScript files
			Unfortunately, such configuration requires us to use inline JavaScript in order to adhere to
			the DRY design methodology as best as possible
		-->
		<script>
			var require =
			{
				baseUrl: '/scripts',
				paths:
				{
					jquery : 'library/jquery/jquery',
					json: 'library/json3/json3',
					superTip: 'library/superTip/superTip'
                },
				deps:
				[
					'foundation/leftHandMenu'
				]
			};
		</script>

		<?php
			if (isset($view->requireJsMainFile))
			{
		?>
				<!-- Load the requireJS library and specify the main file to pull all required dependencies -->
				<script src='scripts/library/requirejs/require.js' data-main='<?php echo $view->requireJsMainFile ?>'></script>
		<?php
			}
			else
			{
		?>
				<!-- Load the requireJS library without specifying a main file, pulling only simple foundational files -->
				<script src='scripts/library/requirejs/require.js'></script>
		<?php
			}
		?>

	</body>
</html>