<?php
	global $view;
?>
<html>
	<head>
		<meta charset="UTF-8" />
	<!-- Forcing IE to adhere to standards here -->
		<meta http-equiv="X-UA-Compatible" content="IE=Edge">

	<!-- Load all the CSS files for this page -->
		<?php
			foreach($view->css as $css)
			{
		?>
				<link rel="stylesheet" type="text/css" href='<?=$css ?>'/>
		<?php
			};
		?>
	</head>
	<body>
		<input type='hidden' id='pageObjectName' value='<?=$view->pageName ?>' />
		<!-- Load all the foundation view files that will be displayed across all pages -->
			<?php
			foreach($view->foundationViews as $html)
			{
				TOS_REQUIRE_ONCE($html);
			}
		?>
		<div class='content'>
			<!-- Load all the view files that comprise the main content for this page -->
			<?php
			foreach($view->contentViews as $html)
			{
				TOS_REQUIRE_ONCE($html);
			}
			?>
		</div>

		<!-- 
			Configure the requireJS engine before using the library to pull external JavaScript files
			Unfortunately, such configuration requires us to use inline JavaScript in order to adhere to
			the DRY design methodology as best as possible
		-->
		<script>
			var require =
			{
				baseURL: 'scripts',
				paths: { jquery : 'library/jquery/jquery' }
			};
		</script>

		<?php
		if (isset($view->requireJsMainFile))
		{
		?>
		<!-- Load all the script files for this page via the main file specified within the page's directory -->
		<script src='scripts/library/requirejs/require.js' data-main="<?php=$view->requireJsMainFile ?>"></script>
		<?php
		}
		?>

	</body>
</html>