<?php
?>

<body>
	<h3>Seems like you lost your way, stranger</h3>
	<p class='center leftPadding rightPadding'>
		You stumbled upon a page that doesn't exist. Don't worry about it, though. Time and
		space is still intact, as far as I'm aware. Just take a second look at that URL and make
		sure that you typed everything correctly. If you think the URL is fine and we're the ones
		that messed up here, drop me a <a href='mailto:kinsho@gmail.com'>message</a> and we'll
		happily prove you wrong.
	</p>
</body>