<?php
?>

<body>
	<h2>The Owl Stakes...</h2>
	<p class='left'>
		A way for you to prove that you truly know football. Week over week, bet points on the teams that you think will pull off upsets. Those who make the best predictions on
		a weekly basis earn the right to call themselves experts...and they will find themselves a few dollars richer.
	</p>
	<p class='left'>
		Well...actually, they'll find themselves more than just a few dollars richer. Quite a bit more, in fact. At the end of the regular season, the top ten predictors can expect
		to win predetermined cash prizes, with the very top predictor bringing home $5,000. On top of that, the ten best predictors each week can expect to see some money as well.
	</p>
	<p class='left'>
		We hope you're intrigued. If so, you may be wondering what it takes to sign up for this contest.
		<br />
		While this contest is open to any adult residing within the United States of America, please keep in mind that participation in this contest is not free. Signing up
		requires that you pay us a $50 fee. Now...we understand if the fee makes you a little hesitant. It's hard to trust strangers over the internet, especially with money. 
		But we've tried taking steps to mitigate any concern you might have here. We're a corporation registered not in Europe or Africa or Asia but in the United States.
		On top of that, as part of the sign-up process, you'll electronically sign an agreement with us that stipulates the terms and conditions of the contest. 
		The agreement is legally binding, so in case we fail to pay out or we fail to do our part in maintaining the contest, you can use the agreement against us in court.
	</p>
	<p class='left'>
		You still might have questions. In that case, we have a 'Rules' page and a 'FAQs' page that hopefully answers any concerns you have. In case you still have questions,
		you're always welcome to e-mail us -<a href='mailto:kinsho@gmail.com'>here</a>-.
	</p>
	<p class='left'>
		We sincerely hope you join us for the regular season.
	</p>
</body>