CREATE TABLE confirms(
  userId INTEGER UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  confirmHash VARCHAR(50) NOT NULL,
  createdOn TIMESTAMP DEFAULT '00-00-0000 00:00:00',
  updatedOn TIMESTAMP DEFAULT now() ON UPDATE now(),
  FOREIGN KEY (userId) REFERENCES users (id)
);

ALTER TABLE confirms MODIFY COLUMN confirmHash VARCHAR(100) NOT NULL;

DESCRIBE confirms;
