CREATE TABLE games(
  id INTEGER UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  homeTeam INTEGER UNSIGNED NOT NULL,
  awayTeam INTEGER UNSIGNED NOT NULL,
  spread DECIMAL(3, 1),
  kickoffTime DATETIME NOT NULL,
  createdOn TIMESTAMP DEFAULT '00-00-0000 00:00:00',
  updatedOn TIMESTAMP DEFAULT now() ON UPDATE now() 
);

ALTER TABLE games ADD COLUMN underdog INTEGER UNSIGNED AFTER awayTeam;
ALTER TABLE games ADD COLUMN didUnderdogWin BIT(0) NOT NULL DEFAULT B'0' AFTER spread;
ALTER TABLE games ADD COLUMN week TINYINT UNSIGNED NOT NULL DEFAULT 1 AFTER didUnderdogWin;

ALTER TABLE games MODIFY COLUMN underdog TINYINT(1) UNSIGNED;
ALTER TABLE games MODIFY COLUMN homeTeam TINYINT(1) UNSIGNED NOT NULL;
ALTER TABLE games MODIFY COLUMN awayTeam TINYINT(1) UNSIGNED NOT NULL;
ALTER TABLE games MODIFY COLUMN week TINYINT(1) UNSIGNED NOT NULL DEFAULT 1;
ALTER TABLE games MODIFY COLUMN didUnderdogWin BOOLEAN DEFAULT NULL;