CREATE TABLE logInCookies(
	username VARCHAR(50) NOT NULL PRIMARY KEY,
	seriesId INTEGER NOT NULL,
	tokenId INTEGER NOT NULL,
	createdOn TIMESTAMP DEFAULT '00-00-0000 00:00:00',
	updatedOn TIMESTAMP DEFAULT now() ON UPDATE now() 
);

ALTER TABLE logInCookies MODIFY COLUMN seriesId VARCHAR(32) NOT NULL;
ALTER TABLE logInCookies MODIFY COLUMN tokenId VARCHAR(32) NOT NULL;

DESCRIBE logInCookies;

SELECT * FROM logInCookies;