CREATE TABLE logInCookies(
	id VARCHAR(32) NOT NULL,
	username VARCHAR(50) NOT NULL PRIMARY KEY,
	createdOn TIMESTAMP DEFAULT '00-00-0000 00:00:00',
	updatedOn TIMESTAMP DEFAULT now() ON UPDATE now() 
);

DESCRIBE logInCookies;

SELECT * FROM logInCookies; 

DROP TABLE logInCookies;