CREATE TABLE teams (
    id INTEGER UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    market VARCHAR(50) NOT NULL,
    name VARCHAR(50) NOT NULL,
    updatedOn TIMESTAMP DEFAULT now() ON UPDATE now()
);

ALTER TABLE teams MODIFY COLUMN id TINYINT NOT NULL AUTO_INCREMENT;