ALTER TABLE users MODIFY COLUMN password VARCHAR(50) NOT NULL;

ALTER TABLE users ADD COLUMN active TINYINT NOT NULL DEFAULT 0;
ALTER TABLE users MODIFY COLUMN active TINYINT NOT NULL DEFAULT 0 AFTER emailAddress;
ALTER TABLE users ADD COLUMN suicidePools VARCHAR(100) DEFAULT '' AFTER active;

DESCRIBE users;
SELECT * FROM users;