CREATE TABLE wagers (
    userId INTEGER UNSIGNED NOT NULL,
	gameId INTEGER UNSIGNED NOT NULL,
	wager TINYINT NOT NULL,
	createdOn TIMESTAMP DEFAULT '00-00-0000 00:00:00',
    updatedOn TIMESTAMP DEFAULT now() ON UPDATE now(),
	PRIMARY KEY (userId, gameId),
	FOREIGN KEY (userId)
		REFERENCES users(id),
	FOREIGN KEY (gameId)
		REFERENCES games(id)
);

ALTER TABLE wagers ADD COLUMN week TINYINT UNSIGNED NOT NULL AFTER wager;

SELECT * FROM wagers;