<?php
	// Set up the reference to the global $view object.
	global $view;
?>

<h3>Your Suicide Pools</h3>

<div class='infoRow center'>
	Please note that if you see <span class='managerLabel'></span> next to a pool name below, that signifies that you are the manager of that pool.
</div>

<fieldset>
	<div class="tabularBorder">

		<?php
			echo $view->poolListingsHTML;
		?>

		<div class='submitButtonFooter'>
			<span class='submitButtonSpan'>
				<input type='button' id='createPoolButton' value='Create A New Pool' />
			</span>
		</div>
	</div>
</fieldset>

<!-- END -->	
<div class='heightener'></div>